# Site settings
author: Radka Kucarova
title: Data Science- My Next Adventure
header-img: img/home-bg.png
email: rkucarova@gmail.com
copyright_name: Radka Kucarova
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and challenges
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rkucar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
